List<String> quotes = [
  "Don we now our ugly sweaters… Let's party! Happy Holidays!",
  "Christmas is the only time of year in which one can sit in front of a dead tree and eat candy out of socks. Enjoy!",
  "Wishing you a white Christmas! (And when you run out of white, just open a bottle of red).",
  "You're a gift in my life. And not the kind I'd return for store credit. Merry Christmas!",
  "A Christmas reminder: Don't try to borrow any money from elves ... they're always a little short! Have a Merry Christmas!",
  "Wishing you hope, peace and lots of Christmas cookies this holiday season!",
  "They say the best Christmas gifts come from the heart … but cash and gift cards do wonders too! Happy Holidays!",
  "Remember, Santa is watching. Everything. Yes, even that. Anyway, Merry Christmas!",
  "Merry Christmas! May your happiness be large and your bills be small.",
  "This holiday season, let's make it a point to cherish what's truly important in our lives: cookies.",
  "I told Santa you were good this year and sent him a link to your Pinterest board. Merry Christmas to you!",
  "This Christmas, may your family be functional and all your batteries be included.",
  "Merry Christmas! I put so much thought into your gift that now it's too late to get it.",
  "Please note: Christmas is canceled. Apparently, you told Santa you have been good this year … he died laughing.",
  "Is it just me, or does Santa look younger every year?",
  "Christmas is mostly for children. But we adults can enjoy it too, until the credit card bills arrive.",
  "Eat. Drink. Be Merry. Have a wonderful Christmas!",
  "May the Christmas Season bring only happiness and joy to you and your family.",
  "The gift of love. The gift of peace. The gift of happiness. May all these be yours at Christmas.",
  "Wishing you a season full of light and laughter for you and your family.",
  "Best wishes for a joyous Christmas filled with love, happiness and prosperity!",
  "May all that is beautiful, meaningful and brings you joy be yours this holiday season and throughout the coming year!",
  "Merry Christmas! Wishing you all the happiness your holiday can hold!",
  "May your holidays sparkle with joy and laughter.",
  "I hope the magic of Christmas fills every corner of your heart and home with joy ",
  "Our family wishes you love, joy and peace … today, tomorrow and always.",
  "May your family have a holiday season that is full of wonderful surprises, treats and nonstop laughter.",
  "Merry Christmas! Wishing you all the best this holiday season!",
  "Wishing you a Christmas that's merry and bright!",
  "We hope you have a safe and relaxing holiday season.",
  "I hope your holiday season is full of peace, joy and happiness.",
  "Merry Christmas with lots of love.",
  "I hope your Christmas is filled with joy this year!",
  "Happy Holidays! I hope all of your Christmas wishes come true.",
  "May your heart be lifted in praise this Christmas for the wonderful gift of Jesus and the joy He brings to our lives.",
  "Merry Christmas! May God bless you richly throughout the year.",
  "Jesus is the reason for the season. Merry Christmas!",
  "May God fill your Yuletide season and all your days with immeasurable prosperity and joy! Merry Christmas!",
  "Sending prayers and hearty Christmas greetings to you. May you receive the most special of God's blessings during this amazing Christmas season!",
  "May you have the gift of faith, the blessing of hope and the peace of His love at Christmas and always!",
  "Merry Christmas! I hope you receive one blessing after another this coming year.",
  "May the Lord grant you and all your loved ones peace, joy and goodwill.",
  "Wishing you a season that's merry and bright with the light of God's love.",
  "May God's blessings be yours this Christmas.",
  "May the wonder of that first Christmas, the joy of God's abundant blessings and the peace of Jesus' presence be with you always.",
  "May the true spirit of Christmas shine in your heart and light your path.",
  "Wishing you and your loved ones a blessed Christmas.",
  "May God bless and keep you during the holiday season and all through the year.",
  "May God bless your life with love and joy this holiday season.",
  "Merry Christmas! May God's love be with you.",
  "May the spirit of Christmas be with you all year round.",
  "You're the most wonderful part of the most wonderful time of the year.",
  "Your love is the best Christmas gift I could ever receive. Merry Christmas, sweetheart!",
  "You're the partridge to my pear tree.",
  "Christmas is more magical now that you're in my life!",
  "Merry Christmas to someone who's sweeter than a candy cane, warms me up more than a cup of hot cocoa and fills my heart with joy more than the biggest present under the tree!",
  "The only thing I love more than Christmas is you.",
  "It's not what's under the tree that matters most, it's who's around it. Every year I'm so grateful to have you there.",
  "You put the merry in my Christmas.",
  "Though we are apart, you are in my heart this Christmas.",
  "Forget the mistletoe, you can kiss me anytime you like.",
  "All I want for Christmas is you.",
  "I'm so lucky to be spending another Christmas with you!",
  "Merry Christmas! You're the best gift I could ask for.",
  "Holidays like Christmas make me so grateful to share life with you.",
  "Christmas is magical because we're together.",
  "All the way from here, I send a special wish, a holiday hug and a holiday kiss!",
  "Far apart during this holiday, but totally together in our hearts and minds. Merry Christmas!",
  "Sending a smile across the miles for a wonderful Christmas!",
  "I may not be nearby, but you are totally in my mind and heart this holiday. Merry Christmas!",
  "Missing you most during this festive time.",
  "We may not be together on Christmas morning, but you're always in my heart.",
  "I wish we could be together this holiday season, but I'm sending warm wishes your way.",
  "I'll miss celebrating with you this Christmas. Eat a few extra cookies for me!",
  "We may not be able to rock around the Christmas tree together, but I'll deck the halls in your honor.",
  "Even though we're apart, our hearts are together.",
  "Let's have a Christmas video call ",
  "Christmas won't be the same without you here.",
  "Even though we're apart, I hope you have a joyous holiday.",
  "Consider this card a raincheck for a belated Christmas hug.",
  "May the magic of the Christmas season fill your home with joy and peace. Sending lots of love to your family.",
  "You've had more than your share of challenges this year. Wishing you peace and hope at Christmas and a new year full of better days.",
  "Sending strength, love and peace to you this holiday season.",
  "My love and thoughts are with you during the Christmas season and the promise of hope it brings.",
  "Hoping that the new year brings you new possibilities.",
  "Wishing you love and light in this challenging season.",
  "I know it's been a hard year for you and your family. I hope the New Year brings better days.",
  "Our hearts are with you and yours, now and always.",
  "Sending you hugs this Christmas season. Take some time to care for yourself.",
  "We know you might be having a difficult time this year, more than ever. Wishing you strength and peace in these challenging times.",
  "Sometimes the holidays can just remind us what we've lost. Remember that I'm always there for you.",
  "I hope the holidays bring a chance to rest and recharge.",
  "May God's love lift you up during this winter of life.",
  "We're always here to support you, if you need a helping hand this holiday.",
  "Warmest wishes that you can find in this shadowy time.",
  "May this season find you among those you love, sharing in the twin glories of generosity and gratitude. ",
  "Christmas is the day that holds all time together. ",
  "I wish we could put up some of the Christmas spirit in jars and open a jar of it every month. ",
  "Christmas will always be as long as we stand heart to heart and hand in hand. ",
  "One of the most glorious messes in the world is the mess created in the living room on Christmas Day. Don't clean it up too quickly. ",
  "Christmas isn't a season. It's a feeling.",
  "A lovely thing about Christmas is that it's compulsory, like a thunderstorm, and we all go through it together. ",
  "Christmas isn't just a day. It's a frame of mind.",
  "Christmas Eve was a night of song that wrapped itself about you like a shawl. But it warmed more than your body. It warmed your heart ... filled it, too, with melody that would last forever. ",
  "Christmas is not an external event at all, but a piece of one's home that one carries in one's heart. ",
  "I prefer the retro chic of spending Christmas just like Joseph and Mary did ",
  "I am not 100 percent certain what a sugarplum is, but for a few weeks every year I've got visions of them dancing in my head anyway. ",
  "The best of all gifts around any Christmas tree: the presence of a happy family all wrapped up in each other. ",
  "Christmas is a season not only of rejoicing but of reflection. ",
  "My idea of Christmas, whether old-fashioned or modern, is very simple: loving others. ",
  "Peace on earth will come to stay, when we live Christmas every day.",
];
